
#TODO Add  Ingress Service 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dnbo-ingress-service
  namespace: dnbo-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: dnbo-cluster-ip-service 
              servicePort: 3000

              # docker build -t dnbo-dte-api



         