apiVersion: v1
kind: Service
metadata: 
    name: dnbo-cluster-ip-service
    namespace: dnbo-prod
spec: 
  type: ClusterIP
  ports: 
    - port: 3000 #allow other pods access to this pod
      targetPort: 3000 #the target port of the containter
  selector: 
    component: dnbo-dte-api 


  