apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: dnbo-ingress-service
  namespace : dnbo-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - http:
      paths:
      - path: /dnbo-dte/?(.*)
        pathType: Prefix
        backend:
          service:
            name: dnbo-cluster-ip-service
            port:
              number: 3000







         