apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnbo-dte 
  namespace: dnbo-prod
spec: 
  replicas: 10 
  selector: 
    matchLabels:
        component: dnbo-dte-api 
  template: 
    metadata:
      labels: 
        component: dnbo-dte-api 
    spec:
      containers: 
      - name: dnbo-dte 
        image: dmp-api-k8s-registry.com:443/dnbo-dte-api:v0.0.6 #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3000 
        env:  
          - name: DBSS_API
            value: https://10.96.34.4:3300
          
          

          
