apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnbo-dte 
  namespace: dnbo-test
spec: 
  replicas: 4 
  selector: 
    matchLabels:
        component: dnbo-dte-api 
  template: 
    metadata:
      labels: 
        component: dnbo-dte-api 
    spec:
      containers: 
      - name: dnbo-dte 
        image: dmp-api-k8s-registry.com:443/dnbo-dte-api:v0.0.2
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3000 
          

          
