apiVersion: v1
kind: Service
metadata: 
    name: nginx-dnbo
    namespace: dnbo-test
spec: 
  type: NodePort
  ports: 
    - port: 3050 #allow other pods access to this pod
      targetPort: 80 #the target port of the containter
      nodePort: 80 #the expose port by the k8s to get  access on browser cluster ip 
  selector: 
    app: nginx-dnbo